### ISSUE TITLE
Typing Backwards...

### ISSUE THREAD

**Issue by AYT04** [bestony/logoly#419]
Whenever a user types `something`, it displays that text backwards.

- Type anything 'anything'
- It displays text backwards

It should just display text as normal, but instead, this happens. Not sure if a release fucked something up. Just wanted to send an Issue here.

---

![bug?](https://github.com/bestony/logoly/assets/153463910/01182b30-7663-4f31-aa8f-68e3ed028473)

**Comment by yldshv** [comment]
Here's a small tip in case someone fixes it before I get to it:

The problem currently only occurs in Firefox because the DOM re-rendering causes the caret to always be placed at the beginning. Chrome handles this more intelligently, which is why the bug doesn't exist there.

## Potential solution approach:
Before changing the value in the store, you could save the caret position, then change the value, and afterward, set the caret to the correct position again.

**Comment by yldshv** [comment]
fixed
